import { tripDays, walletItems, hotels, emergencyContacts, packingChecklist, pendingItems, phrases } from './trip-data.js';
import { resolveInitialDayIndex, getDayTemporalState, formatCountdown, mapsUrl, wazeUrl, uberUrl, localDateKey } from './core.js';

const state = { tab:'today', dayIndex:resolveInitialDayIndex(tripDays, new Date()), wakeLock:null };
const main = document.querySelector('#app-main');
const deviceDate = document.querySelector('#device-date');
const networkPill = document.querySelector('#network-pill');
const modal = document.querySelector('#ticket-modal');
const modalCode = document.querySelector('#ticket-code');
const modalTitle = document.querySelector('#ticket-title');
const modalNote = document.querySelector('#ticket-note');
const modalFull = document.querySelector('#ticket-full');
const modalFullToggle = document.querySelector('#ticket-full-toggle');

const esc = (s='') => String(s).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const weekday = new Intl.DateTimeFormat('pt-BR',{weekday:'short'});
const monthDay = new Intl.DateTimeFormat('pt-BR',{day:'numeric',month:'long'});
const deviceFmt = new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'numeric',month:'long'});
function parseDayDate(dateKey){ const [y,m,d]=dateKey.split('-').map(Number); return new Date(y,m-1,d,12); }
function prettyDay(dateKey){ const d=parseDayDate(dateKey); return `${weekday.format(d).replace('.','').toUpperCase()} · ${monthDay.format(d).toUpperCase()}`; }
function updateDeviceDate(){ const s=deviceFmt.format(new Date()); deviceDate.textContent=s.charAt(0).toUpperCase()+s.slice(1); }
function updateNetwork(){ const online=navigator.onLine; networkPill.textContent=online?'online':'offline · roteiro salvo'; networkPill.classList.toggle('offline',!online); }
function navActions(location){ if(!location) return ''; return `<a class="action-link" data-kind="uber" href="${esc(uberUrl(location))}" target="_blank" rel="noopener">UBER</a><a class="action-link" data-kind="maps" href="${esc(mapsUrl(location))}" target="_blank" rel="noopener">MAPS</a><a class="action-link" data-kind="waze" href="${esc(wazeUrl(location))}" target="_blank" rel="noopener">WAZE</a>`; }
function ticketButton(ticketId){ if(!ticketId) return ''; const item=walletItems.find(i=>i.id===ticketId); if(!item?.codeAsset) return ''; return `<button class="ticket-button" data-ticket="${esc(ticketId)}">${item.category==='Voos'?'BOARDING':'QR / TICKET'}</button>`; }
function eventCard(event){ const hasActions=event.location || (event.ticketId && walletItems.some(i=>i.id===event.ticketId && i.codeAsset)); return `<article class="event-card"><div class="event-dot">${esc(event.icon || '•')}</div><div class="event-time">${esc(event.time)}${event.end?`–${esc(event.end)}`:''}</div><h3>${esc(event.title)}</h3>${event.location?`<div class="event-note">📍 ${esc(event.location.destination)}</div>`:''}${event.note?`<div class="event-note">${esc(event.note)}</div>`:''}${event.perrengue?`<div class="perrengue"><b>EVITAR PERRENGUE</b><br>${esc(event.perrengue)}</div>`:''}${hasActions?`<div class="actions">${ticketButton(event.ticketId)}${navActions(event.location)}</div>`:''}</article>`; }
function getBeforeTripBanner(day){ const now=new Date(); const first=parseDayDate(tripDays[0].date); const today=localDateKey(now); if(today<tripDays[0].date){ const days=Math.ceil((first-new Date(now.getFullYear(),now.getMonth(),now.getDate(),12))/86400000); return `<div class="pretrip-banner"><b>PRÓXIMA VIAGEM:</b> faltam ${Math.max(0,days)} dias. A Home já abre no primeiro dia para revisão.</div>`; } if(today>tripDays.at(-1).date) return `<div class="pretrip-banner"><b>VIAGEM CONCLUÍDA.</b> O roteiro permanece disponível offline como diário.</div>`; if(day.date!==today) return `<div class="pretrip-banner">Você está vendo ${prettyDay(day.date)}. Deslize para voltar ao dia atual da viagem.</div>`; return ''; }
function statusCards(day){ const now=new Date(); const today=localDateKey(now); let temporal={current:null,next:null,nextAt:null}; if(day.date===today) temporal=getDayTemporalState(day,now); else if(day.date>today){ temporal.next=day.events.find(e=>/^\d{2}:\d{2}$/.test(e.time)); } const current=temporal.current; const next=temporal.next; let nextMeta=''; if(next){ nextMeta=`${esc(next.time)}${next.end?`–${esc(next.end)}`:''}`; if(temporal.nextAt) nextMeta+=` <span class="countdown">${esc(formatCountdown(temporal.nextAt-now))}</span>`; } return `<div class="status-grid"><div class="status-card"><div class="status-card__label">AGORA</div><div class="status-card__icon">${esc(current?.icon || (day.date===today?'⌁':'◌'))}</div><div class="status-card__title">${esc(current?.title || (day.date===today?'Sem atividade em andamento':'Dia selecionado'))}</div><div class="status-card__meta">${current?`${esc(current.time)}${current.end?`–${esc(current.end)}`:''}`:esc(day.city)}</div></div><div class="status-card next"><div class="status-card__label">PRÓXIMO</div><div class="status-card__icon">${esc(next?.icon || '→')}</div><div class="status-card__title">${esc(next?.title || 'Sem próximo compromisso')}</div><div class="status-card__meta">${nextMeta || esc(day.summary)}</div></div></div>`; }
function renderToday(){ const day=tripDays[state.dayIndex]; main.innerHTML=`<section id="today-swipe"><div class="hero"><div class="hero__nav"><button class="day-arrow" id="prev-day" ${state.dayIndex===0?'disabled':''} aria-label="Dia anterior">‹</button><div class="hero__date">${prettyDay(day.date)} · DIA ${state.dayIndex+1}/${tripDays.length}</div><button class="day-arrow" id="next-day" ${state.dayIndex===tripDays.length-1?'disabled':''} aria-label="Próximo dia">›</button></div><h1>${esc(day.title)}</h1><div class="hero__summary"><b>${esc(day.city)}</b><br>${esc(day.summary)}</div>${getBeforeTripBanner(day)}</div>${statusCards(day)}<section class="section"><div class="info-pair"><div class="info-card"><h3>O QUE VESTIR</h3><div class="chips">${day.wear.map(x=>`<span class="chip">👕 ${esc(x)}</span>`).join('')}</div></div><div class="info-card"><h3>O QUE LEVAR</h3><div class="chips">${day.bring.map(x=>`<span class="chip">＋ ${esc(x)}</span>`).join('')}</div></div></div>${day.alerts?.map(a=>`<div class="alert-box"><strong>ATENÇÃO</strong>${esc(a)}</div>`).join('')||''}</section><section class="section"><div class="section-title"><div><div class="section-kicker">PROGRAMAÇÃO</div><h2>Timeline do dia</h2></div></div><div class="timeline">${day.events.map(eventCard).join('')}</div></section></section>`; bindToday(); bindTicketButtons(); }
function renderRoute(){ main.innerHTML=`<header class="page-header"><div class="eyebrow">15 DIAS · 3 PAÍSES</div><h1>Roteiro</h1><p>Toque em qualquer dia para abrir a programação completa.</p></header><div class="route-list">${tripDays.map((day,i)=>`<button class="route-day" data-day="${i}"><span class="route-day__date">${prettyDay(day.date).split('·')[1] || prettyDay(day.date)}</span><span><span class="route-day__title">${esc(day.title)}</span><span class="route-day__city">${esc(day.city)}</span></span><span class="route-day__arrow">›</span></button>`).join('')}</div>`; main.querySelectorAll('[data-day]').forEach(btn=>btn.addEventListener('click',()=>{state.dayIndex=Number(btn.dataset.day);setTab('today');})); }
function walletItemHtml(item){ return `<article class="wallet-item"><div><div class="wallet-item__title">${esc(item.title)}</div><div class="wallet-item__meta">${esc(item.date)} · ${esc(item.subtitle||'')}</div>${item.locator?`<div class="wallet-item__meta">Localizador: <b>${esc(item.locator)}</b></div>`:''}${item.note?`<div class="wallet-item__note">${esc(item.note)}</div>`:''}</div><div class="wallet-actions">${item.codeAsset?`<button class="mini-button primary" data-ticket="${esc(item.id)}">ABRIR CÓDIGO</button>`:''}${item.ticketAsset?`<button class="mini-button" data-full-ticket="${esc(item.id)}">TICKET</button>`:''}</div></article>`; }
function renderWallet(){ const cats=[...new Set(walletItems.map(i=>i.category))]; main.innerHTML=`<header class="page-header"><div class="eyebrow">OFFLINE · ACESSO RÁPIDO</div><h1>Carteira</h1><p>Tickets e confirmações essenciais.</p></header>${cats.map(cat=>`<section class="wallet-section"><h2>${esc(cat)}</h2><div class="wallet-group">${walletItems.filter(i=>i.category===cat).map(walletItemHtml).join('')}</div></section>`).join('')}<section class="wallet-section"><h2>Hotéis</h2><div class="wallet-group">${hotels.map(h=>`<article class="hotel-card"><h3>${esc(h.city)} · ${esc(h.name)}</h3><p>${esc(h.dates)} · confirmação <b>${esc(h.confirmation)}</b> · PIN <b>${esc(h.pin)}</b></p><div class="hotel-actions"><a href="${esc(mapsUrl({destination:h.destination,name:h.name}))}" target="_blank" rel="noopener">MAPS</a><a href="${esc(wazeUrl({destination:h.destination,name:h.name}))}" target="_blank" rel="noopener">WAZE</a><a href="${esc(uberUrl({destination:h.destination,name:h.name}))}" target="_blank" rel="noopener">UBER</a></div></article>`).join('')}</div></section>`; bindTicketButtons(); main.querySelectorAll('[data-full-ticket]').forEach(btn=>btn.addEventListener('click',()=>openTicket(btn.dataset.fullTicket,true))); }
function renderMore(){ main.innerHTML=`<header class="page-header"><div class="eyebrow">SUPORTE · DOCUMENTOS · PLANO B</div><h1>Mais</h1><p>Informações importantes e pendências.</p></header><div class="more-grid"><section class="more-card"><h3>Instalar no iPhone</h3><div class="install-steps"><div class="install-step">Abra este site no <b>Safari</b>.</div><div class="install-step">Toque em <b>Compartilhar</b>.</div><div class="install-step">Escolha <b>Adicionar à Tela de Início</b>.</div></div></section><section class="more-card"><h3>Pendências</h3><ul class="checklist">${pendingItems.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section class="more-card"><h3>Emergência e contatos</h3>${emergencyContacts.map(c=>`<div class="contact-row"><span>${esc(c.label)}</span><a href="${esc(c.href)}">${esc(c.value)}</a></div>`).join('')}</section><section class="more-card"><h3>Checklist essencial</h3><ul class="checklist">${packingChecklist.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>${Object.entries(phrases).map(([lang,items])=>`<section class="more-card"><h3>${esc(lang)}</h3><div class="phrase-grid">${items.map(([pt,local])=>`<span>${esc(pt)}</span><b>${esc(local)}</b>`).join('')}</div></section>`).join('')}<section class="more-card"><h3>Offline</h3><p>Roteiro e informações são armazenados após a primeira abertura online. Uber, Maps e Waze precisam de conexão.</p></section></div>`; }
function render(){ updateDeviceDate(); updateNetwork(); if(state.tab==='today') renderToday(); if(state.tab==='route') renderRoute(); if(state.tab==='wallet') renderWallet(); if(state.tab==='more') renderMore(); }
function setTab(tab){ state.tab=tab; document.querySelectorAll('.nav-button').forEach(btn=>btn.classList.toggle('is-active',btn.dataset.tab===tab)); render(); main.focus({preventScroll:true}); window.scrollTo({top:0,behavior:'instant'}); }
function bindToday(){ document.querySelector('#prev-day')?.addEventListener('click',()=>changeDay(-1)); document.querySelector('#next-day')?.addEventListener('click',()=>changeDay(1)); const surface=document.querySelector('#today-swipe'); let startX=0,startY=0; surface?.addEventListener('touchstart',e=>{const t=e.changedTouches[0];startX=t.screenX;startY=t.screenY;},{passive:true}); surface?.addEventListener('touchend',e=>{const t=e.changedTouches[0];const dx=t.screenX-startX,dy=t.screenY-startY;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.35) changeDay(dx<0?1:-1);},{passive:true}); }
function changeDay(delta){ const next=Math.max(0,Math.min(tripDays.length-1,state.dayIndex+delta)); if(next!==state.dayIndex){state.dayIndex=next;renderToday();window.scrollTo({top:0,behavior:'smooth'});} }
function bindTicketButtons(){ main.querySelectorAll('[data-ticket]').forEach(btn=>btn.addEventListener('click',()=>openTicket(btn.dataset.ticket,false))); }
async function requestWakeLock(){ try{ if('wakeLock' in navigator) state.wakeLock=await navigator.wakeLock.request('screen'); }catch{} }
async function releaseWakeLock(){ try{ await state.wakeLock?.release(); }catch{} state.wakeLock=null; }
function openTicket(id,showFull=false){ const item=walletItems.find(i=>i.id===id); if(!item) return; modalTitle.textContent=item.title; modalNote.textContent=item.note||item.subtitle||''; modalCode.hidden=!item.codeAsset; if(item.codeAsset) modalCode.src=item.codeAsset; modalFull.hidden=true; modalFull.removeAttribute('src'); modalFullToggle.hidden=!item.ticketAsset; modalFullToggle.textContent=showFull?'OCULTAR TICKET COMPLETO':'VER TICKET COMPLETO'; if(showFull&&item.ticketAsset){modalFull.src=item.ticketAsset;modalFull.hidden=false;modalFullToggle.textContent='OCULTAR TICKET COMPLETO';} modalFullToggle.onclick=()=>{const hiding=!modalFull.hidden;if(hiding){modalFull.hidden=true;modalFullToggle.textContent='VER TICKET COMPLETO';}else{modalFull.src=item.ticketAsset;modalFull.hidden=false;modalFullToggle.textContent='OCULTAR TICKET COMPLETO';}}; modal.hidden=false;document.body.style.overflow='hidden';requestWakeLock(); }
async function closeTicket(){ modal.hidden=true;document.body.style.overflow='';modalCode.removeAttribute('src');modalFull.removeAttribute('src');await releaseWakeLock(); }
document.querySelectorAll('.nav-button').forEach(btn=>btn.addEventListener('click',()=>setTab(btn.dataset.tab)));
document.querySelector('#ticket-close').addEventListener('click',closeTicket);
window.addEventListener('online',updateNetwork); window.addEventListener('offline',updateNetwork);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&!modal.hidden)requestWakeLock();});
if('serviceWorker' in navigator){ window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{})); }
render(); setInterval(()=>{updateDeviceDate();if(state.tab==='today')renderToday();},60000);
