const loc=(name,destination)=>({name,destination});
const ev=(time,title,options={})=>({time,title,...options});

export const tripDays=[
{date:'2026-09-07',city:'Dubrovnik',title:'Chegada Dubrovnik',summary:'Chegada ao Adriático, check-in na Old Town e jantar leve.',wear:['Roupa de viagem confortável','Tênis','Moletom leve'],bring:['Passaporte','Celular + carregador','Confirmação do hotel'],alerts:['Não ativar o Dubrovnik Pass hoje; ativar amanhã para aproveitar as 72h.'],events:[ev('19:00','Pouso em Dubrovnik (DBV)',{end:'19:30',icon:'✈️',location:loc('Aeroporto de Dubrovnik','Dubrovnik Airport, Čilipi, Croatia')}),ev('19:30','Táxi ou Uber para a Old Town',{end:'20:20',icon:'🚕',location:loc('Lausa Dubrovnik Rooms','Lausa Dubrovnik Rooms, Dubrovnik, Croatia'),perrengue:'Com bagagem grande, evitar ônibus.'}),ev('20:30','Check-in Lausa Dubrovnik Rooms',{end:'21:00',icon:'🏨',location:loc('Lausa Dubrovnik Rooms','Lausa Dubrovnik Rooms, Dubrovnik, Croatia')}),ev('21:00','Jantar Lady Pi-Pi',{end:'22:15',icon:'🍽️',location:loc('Lady Pi-Pi','Lady Pi-Pi, Peline 1, Dubrovnik, Croatia')})]},
{date:'2026-09-08',city:'Dubrovnik',title:'Muralhas · Lovrijenac · Monte Srđ',summary:'Dubrovnik Pass, muralhas cedo e pôr do sol no Monte Srđ.',wear:['Tênis fechado','Boné','Roupa leve'],bring:['Dubrovnik Pass','1 L de água/pessoa','Protetor 50+'],alerts:['QR do ônibus do Dubrovnik Pass funciona uma vez; guardar o ticket impresso.'],events:[ev('07:30','Ativar Dubrovnik Pass na Porta Pile',{end:'07:45',icon:'🎟️',location:loc('Pile Gate','Pile Gate, Dubrovnik, Croatia')}),ev('07:45','Muralhas Medievais',{end:'09:30',icon:'🏰',location:loc('Dubrovnik City Walls','Dubrovnik City Walls, Pile Gate, Dubrovnik, Croatia'),perrengue:'Entrar antes das 8h para evitar calor e lotação.'}),ev('09:30','Fortaleza Lovrijenac + Stradun',{end:'10:30',icon:'🏯',location:loc('Fort Lovrijenac','Fort Lovrijenac, Dubrovnik, Croatia')}),ev('13:00','Almoço Proto',{end:'14:30',icon:'🍽️',location:loc('Proto','Proto Fish Restaurant, Široka 1, Dubrovnik, Croatia')}),ev('17:30','Subida ao Monte Srđ',{end:'19:00',icon:'🥾',location:loc('Mount Srđ','Mount Srđ, Dubrovnik, Croatia')}),ev('19:00','Pôr do sol no Monte Srđ',{end:'20:00',icon:'🌅',location:loc('Mount Srđ summit','Mount Srđ, Dubrovnik, Croatia')})]},
{date:'2026-09-09',city:'Dubrovnik → Budapest',title:'Lokrum + voo + Budapest',summary:'Manhã de mar em Lokrum, voo Wizz Air e chegada a Budapest.',wear:['Biquíni/sunga por baixo','Roupa leve','Casaco leve'],bring:['Toalha','Passaporte','Boarding pass Wizz Air','Powerbank'],alerts:['Porta do voo fecha 13h40.','Confirmar o último ferry de Lokrum.'],events:[ev('08:00','Ferry para Lokrum',{end:'08:30',icon:'⛴️',location:loc('Old Port Dubrovnik','Old Port, Dubrovnik, Croatia')}),ev('08:30','Lokrum: lago salgado e ilha',{end:'10:45',icon:'🏝️',location:loc('Lokrum Island','Lokrum, Dubrovnik, Croatia')}),ev('11:30','Checkout Lausa',{end:'12:30',icon:'🧳',location:loc('Lausa Dubrovnik Rooms','Lausa Dubrovnik Rooms, Dubrovnik, Croatia')}),ev('13:00','Ir para o aeroporto DBV',{end:'13:40',icon:'🚕',location:loc('Dubrovnik Airport','Dubrovnik Airport, Čilipi, Croatia'),perrengue:'Porta fecha 13h40.'}),ev('14:10','W6 2256 Dubrovnik → Budapest',{end:'15:30',icon:'✈️',note:'Henrique 4B · Cibele 4A · confirmação KWKWWW.'}),ev('16:30','Check-in Up Hotel Budapest',{end:'18:00',icon:'🏨',location:loc('Up Hotel Budapest','Up Hotel Budapest, Csengery utca 31, Budapest, Hungary')}),ev('20:00','Jewish Quarter + Szimpla Kert',{icon:'🌙',location:loc('Szimpla Kert','Szimpla Kert, Kazinczy utca 14, Budapest, Hungary')})]},
{date:'2026-09-10',city:'Budapest',title:'Castelo · Széchenyi · Ruin Bars',summary:'Café histórico, Buda, termas e noite no bairro judeu.',wear:['Tênis','Roupa confortável','Casaco para a noite'],bring:['Roupa de banho','Toalha','Bilhete BKK'],alerts:['Amanhã sair do hotel às 05h45 para o FlixBus das 06h45.'],events:[ev('08:30','New York Café',{end:'09:45',icon:'☕',location:loc('New York Café','New York Café, Erzsébet körút 9-11, Budapest, Hungary')}),ev('10:00','Castelo de Buda + Bastião dos Pescadores',{end:'12:00',icon:'🏰',location:loc('Fisherman’s Bastion','Fisherman’s Bastion, Budapest, Hungary')}),ev('14:30','Széchenyi Thermal Bath',{end:'16:15',icon:'♨️',location:loc('Széchenyi Thermal Bath','Széchenyi Thermal Bath, Budapest, Hungary')}),ev('18:30','Szimpla Kert',{end:'19:45',icon:'🍻',location:loc('Szimpla Kert','Szimpla Kert, Kazinczy utca 14, Budapest, Hungary')}),ev('20:00','Jantar Borkonyha',{icon:'🍽️',location:loc('Borkonyha','Borkonyha Winekitchen, Sas utca 3, Budapest, Hungary'),perrengue:'Reservar.'})]},
{date:'2026-09-11',city:'Budapest → Ljubljana',title:'FlixBus · Ljubljana · carro',summary:'Ônibus cedo, chegada à Eslovênia, carro e centro histórico.',wear:['Roupa confortável de viagem','Tênis','Moletom'],bring:['Passaporte à mão','Ticket FlixBus','PID','Reserva do carro'],alerts:['Controles na fronteira podem atrasar.','Não entrar de carro no centro histórico de Ljubljana.'],events:[ev('05:45','Sair do Up Hotel para Népliget',{end:'06:15',icon:'🚕',location:loc('Népliget Bus Station','Budapest Népliget Bus Station, Üllői út 131, Budapest, Hungary')}),ev('06:15','Embarque FlixBus Rota 403',{end:'06:45',icon:'🎫',location:loc('Népliget','Budapest Népliget Bus Station, Üllői út 131, Budapest, Hungary'),perrengue:'Henrique 11B · Cibele 11A · passaporte à mão.'}),ev('06:45','FlixBus Budapest → Ljubljana',{end:'12:50',icon:'🚌'}),ev('12:50','Chegada Ljubljana Bus Station',{end:'13:30',icon:'📍',location:loc('Ljubljana Bus Station','Ljubljana Bus Station, Trg Osvobodilne fronte 4, Ljubljana, Slovenia')}),ev('13:30','Retirar carro alugado',{end:'14:00',icon:'🚗',note:'Confirmar locadora e cross-border.'}),ev('14:00','Check-in Under The Castle',{end:'15:00',icon:'🏨',location:loc('Under The Castle Apartments','Under The Castle Apartments, Ljubljana, Slovenia')}),ev('16:30','Castelo de Ljubljana',{end:'18:30',icon:'🏰',location:loc('Ljubljana Castle','Ljubljana Castle, Slovenia')})]},
{date:'2026-09-12',city:'Bled + Vintgar',title:'Lago alpino · castelo · nadar',summary:'Vintgar cedo, Ilha de Bled e mergulho no lago.',wear:['Biquíni/sunga por baixo','Tênis','Sandália na mochila'],bring:['Toalha','Água','Roupa seca'],alerts:['Vintgar: piso molhado e escorregadio.'],events:[ev('07:30','Drive Ljubljana → Vintgar',{end:'08:15',icon:'🚗',location:loc('Vintgar Gorge','Vintgar Gorge, Slovenia')}),ev('08:15','Vintgar Gorge',{end:'10:00',icon:'🥾',location:loc('Vintgar Gorge','Vintgar Gorge, Slovenia'),perrengue:'Tênis obrigatório; chão molhado.'}),ev('10:30','Barco Pletna para Ilha de Bled',{end:'12:00',icon:'🚣',location:loc('Lake Bled','Lake Bled, Slovenia')}),ev('12:00','Castelo de Bled + mirantes',{end:'14:30',icon:'🏰',location:loc('Bled Castle','Bled Castle, Slovenia')}),ev('15:00','Nadar no Lago Bled',{end:'17:00',icon:'🏊',location:loc('Lake Bled','Lake Bled, Slovenia')}),ev('20:00','Jantar TaBar',{icon:'🍽️',location:loc('TaBar','TaBar, Ljubljana, Slovenia')})]},
{date:'2026-09-13',city:'Ljubljana → Rovinj',title:'Postojna · Predjama · Ístria',summary:'Cavernas frias, castelo no penhasco e chegada ao Adriático.',wear:['Agasalho','Tênis','Roupa leve para Rovinj'],bring:['Ingressos Postojna/Predjama','Água','Casaco'],alerts:['Postojna fica perto de 10°C.','Old Town de Rovinj não aceita carro.'],events:[ev('07:30','Drive Ljubljana → Postojna',{end:'08:30',icon:'🚗',location:loc('Postojna Cave','Postojna Cave, Slovenia')}),ev('08:30','Grutas de Postojna',{end:'10:30',icon:'🕳️',location:loc('Postojna Cave','Postojna Cave, Slovenia'),perrengue:'Levar agasalho.'}),ev('10:45','Castelo de Predjama',{end:'12:00',icon:'🏰',location:loc('Predjama Castle','Predjama Castle, Slovenia')}),ev('12:15','Drive para Rovinj',{end:'15:00',icon:'🚗',location:loc('Valdibora Parking','Valdibora Parking, Rovinj, Croatia')}),ev('16:00','Check-in Charmy Rovinj',{end:'17:00',icon:'🏨',location:loc('Charmy Rovinj','Charmy Rovinj, Rovinj, Croatia')}),ev('18:00','Santa Eufêmia + pôr do sol',{end:'19:30',icon:'🌅',location:loc('St. Euphemia Church','Church of St. Euphemia, Rovinj, Croatia')})]},
{date:'2026-09-14',city:'Pula · Motovun · Grožnjan',title:'Arena romana · trufas · arte',summary:'Ruínas romanas, interior da Ístria e vilas medievais.',wear:['Tênis','Roupa leve'],bring:['Água','Óculos de sol','Reserva/restaurante'],alerts:['Motovun e Grožnjan têm calçamento medieval.'],events:[ev('08:30','Drive Rovinj → Pula',{end:'09:00',icon:'🚗',location:loc('Pula Arena','Pula Arena, Pula, Croatia')}),ev('09:00','Arena de Pula',{end:'10:30',icon:'🏛️',location:loc('Pula Arena','Pula Arena, Pula, Croatia')}),ev('13:00','Drive Pula → Motovun',{end:'14:00',icon:'🚗',location:loc('Motovun','Motovun, Croatia')}),ev('14:00','Motovun',{end:'15:30',icon:'🏰',location:loc('Motovun','Motovun, Croatia')}),ev('15:30','Grožnjan',{end:'16:30',icon:'🎨',location:loc('Grožnjan','Grožnjan, Croatia')}),ev('20:00','Jantar Puntulina',{icon:'🍽️',location:loc('Puntulina','Puntulina, Svetog Križa 38, Rovinj, Croatia'),perrengue:'Reservar.'})]},
{date:'2026-09-15',city:'Cabo Kamenjak',title:'Praia total · snorkel · 23°C',summary:'Enseadas turquesa, snorkel e picnic.',wear:['Biquíni/sunga desde manhã','Aqua-shoes','Roupa leve'],bring:['1,5 L água/pessoa','Comida/picnic','Toalha','Protetor 50+'],alerts:['Sem infraestrutura: levar tudo e trazer o lixo de volta.','Últimos quilômetros em estrada de terra.'],events:[ev('09:00','Comprar picnic',{end:'10:00',icon:'🥖',location:loc('Rovinj Market','Rovinj Market, Croatia')}),ev('10:00','Drive Rovinj → Kamenjak',{end:'10:50',icon:'🚗',location:loc('Cape Kamenjak','Cape Kamenjak, Premantura, Croatia'),perrengue:'Estrada de terra no final; ir devagar.'}),ev('11:00','Praia + snorkel + picnic',{end:'16:00',icon:'🤿',location:loc('Cape Kamenjak','Cape Kamenjak, Premantura, Croatia')}),ev('16:45','Volta para Rovinj',{end:'18:00',icon:'🚗',location:loc('Rovinj','Rovinj, Croatia')}),ev('20:00','Jantar Orca',{icon:'🍽️',location:loc('Orca','Restaurant Orca, Rovinj, Croatia')})]},
{date:'2026-09-16',city:'Rovinj → Plitvice',title:'Rastoke · cascatas · Plitvice',summary:'Mini-Plitvice em Rastoke e noite perto do parque.',wear:['Roupa confortável','Tênis','Capa de chuva'],bring:['Reserva Villa Prica','Ingresso Plitvice','Água'],alerts:['Dormir cedo para entrada matinal em Plitvice.'],events:[ev('08:00','Drive Rovinj → Rastoke',{end:'09:50',icon:'🚗',location:loc('Rastoke','Rastoke, Slunj, Croatia')}),ev('10:00','Explorar Rastoke',{end:'11:30',icon:'💦',location:loc('Rastoke','Rastoke, Slunj, Croatia')}),ev('12:00','Almoço em Rastoke',{end:'13:30',icon:'🍽️',location:loc('Rastoke','Rastoke, Slunj, Croatia')}),ev('13:30','Drive Rastoke → Plitvice',{end:'14:00',icon:'🚗',location:loc('Villa Prica','Villa Prica, Plitvica Selo 32, Croatia')}),ev('14:00','Check-in Villa Prica',{end:'15:00',icon:'🏨',location:loc('Villa Prica','Villa Prica, Plitvica Selo 32, Croatia')}),ev('22:00','Dormir cedo',{icon:'🌙'})]},
{date:'2026-09-17',city:'Plitvice → Split',title:'Percurso H · devolver carro · Split',summary:'Lagos de Plitvice, roadtrip final e chegada a Split.',wear:['Tênis','Capa de chuva','Roupa confortável'],bring:['Ingresso Plitvice','Água','Documentos do carro'],alerts:['Proibido nadar em Plitvice.','Devolver carro com tanque cheio e fotografar km/estado.'],events:[ev('06:30','Café na Villa Prica',{end:'07:15',icon:'☕',location:loc('Villa Prica','Villa Prica, Plitvica Selo 32, Croatia')}),ev('07:30','Percurso H Plitvice',{end:'14:00',icon:'🥾',location:loc('Plitvice Entrance 1','Plitvice Lakes National Park Entrance 1, Croatia'),perrengue:'Tênis e capa de chuva.'}),ev('16:30','Drive Plitvice → Split',{end:'19:15',icon:'🚗',location:loc('Split Airport','Split Airport, Croatia')}),ev('19:15','Devolver carro SPU',{end:'20:00',icon:'🚗',location:loc('Split Airport','Split Airport, Croatia'),perrengue:'Tanque cheio e fotos do carro.'}),ev('20:00','Táxi para Little Lion',{end:'20:45',icon:'🚕',location:loc('Little Lion','Little Lion, Split, Croatia')})]},
{date:'2026-09-18',city:'Split',title:'Diocleciano · Klis · Bačvice',summary:'Roma antiga, Fortaleza de Klis e praia.',wear:['Biquíni/sunga','Tênis','Sandália na mochila'],bring:['Toalha','Protetor solar','Água'],alerts:['Verificar horário de retorno do ônibus 22 para Klis.'],events:[ev('08:30','Palácio de Diocleciano',{end:'10:00',icon:'🏛️',location:loc('Diocletian’s Palace','Diocletian’s Palace, Split, Croatia')}),ev('10:00','Fortaleza de Klis',{end:'12:30',icon:'🏰',location:loc('Klis Fortress','Klis Fortress, Klis, Croatia')}),ev('13:00','Almoço Fife',{end:'14:15',icon:'🍽️',location:loc('Fife','Fife, Trumbićeva obala 11, Split, Croatia')}),ev('14:30','Parque Marjan',{end:'16:00',icon:'🥾',location:loc('Marjan Forest Park','Marjan Forest Park, Split, Croatia')}),ev('16:00','Praia Bačvice',{end:'18:30',icon:'🏖️',location:loc('Bačvice Beach','Bačvice Beach, Split, Croatia')})]},
{date:'2026-09-19',city:'Krka',title:'7 cachoeiras · natureza',summary:'Bate-volta a Krka e fim de tarde em Split.',wear:['Roupa leve','Tênis'],bring:['Toalha','Protetor solar','Reserva do tour','Água'],alerts:['Confirmar tour, ponto exato de encontro e regras atuais do parque.'],events:[ev('08:30','Tour Split → Krka',{end:'09:30',icon:'🚌',location:loc('Krka National Park','Krka National Park, Croatia')}),ev('09:30','Krka + Skradinski Buk',{end:'13:30',icon:'💦',location:loc('Skradinski Buk','Skradinski Buk, Krka National Park, Croatia'),perrengue:'Confirmar regras atuais de banho.'}),ev('15:30','Transfer de volta a Split',{end:'17:00',icon:'🚌',location:loc('Split','Split, Croatia')}),ev('17:00','Praia Kaštelet',{end:'18:30',icon:'🏖️',location:loc('Kaštelet Beach','Kaštelet Beach, Split, Croatia')})]},
{date:'2026-09-20',city:'Vis',title:'Ferry · Komiža · Stiniva',summary:'Ilha de Vis, vila de pescadores e enseada entre falésias.',wear:['Biquíni/sunga','Aqua-shoes','Roupa leve'],bring:['Bilhete do ferry','Toalha','Protetor solar','Água'],alerts:['Confirmar ida e volta Jadrolinija antes de sair.'],events:[ev('08:00','Ferry Split → Vis',{end:'10:15',icon:'⛴️',location:loc('Split Ferry Port','Split Ferry Port, Obala kneza Domagoja, Split, Croatia')}),ev('10:15','Vis Town',{end:'11:00',icon:'🏘️',location:loc('Vis Town','Vis, Croatia')}),ev('11:00','Táxi/scooter para Komiža',{end:'12:00',icon:'🚕',location:loc('Komiža','Komiža, Vis, Croatia')}),ev('13:00','Almoço Konoba Bako',{end:'14:15',icon:'🍽️',location:loc('Konoba Bako','Konoba Bako, Komiža, Vis, Croatia')}),ev('14:30','Stiniva',{end:'17:00',icon:'🏊',location:loc('Stiniva Cove','Stiniva Cove, Vis, Croatia'),perrengue:'Reconfirmar o ferry de volta antes.'}),ev('17:30','Retorno Vis → Split',{end:'19:45',icon:'⛴️',location:loc('Vis Ferry Port','Vis Ferry Port, Vis, Croatia')})]},
{date:'2026-09-21',city:'Split → Dubrovnik → Brasil',title:'Bačvice · compras · ônibus · voo',summary:'Último mergulho, compras, ônibus e voo ao Brasil.',wear:['Roupa de banho pela manhã','Roupa de viagem','Tênis confortável'],bring:['Passaporte à mão','Boarding pass','Toalha','Bagagem completa'],alerts:['Passaporte à mão durante o ônibus.','Boarding previsto 19h15 para voo 19h50.'],events:[ev('09:00','Último mergulho em Bačvice',{end:'10:30',icon:'🏖️',location:loc('Bačvice Beach','Bačvice Beach, Split, Croatia')}),ev('11:00','Compras no Pazar',{end:'12:00',icon:'🛍️',location:loc('Pazar Market','Pazar Market, Split, Croatia')}),ev('13:00','Ônibus Split → Dubrovnik',{end:'17:30',icon:'🚌',location:loc('Split Bus Station','Split Bus Station, Obala kneza Domagoja 12, Split, Croatia')}),ev('17:30','Táxi para DBV',{end:'18:20',icon:'🚕',location:loc('Dubrovnik Airport','Dubrovnik Airport, Čilipi, Croatia')}),ev('19:15','Boarding LA1814',{end:'19:50',icon:'🎫',location:loc('Dubrovnik Airport','Dubrovnik Airport, Čilipi, Croatia')}),ev('19:50','DBV → MAD → GRU',{icon:'✈️',note:'LA1814 + LA1572 · chegada GRU 22/set 05h55.'})]}
];

export const walletItems=[
{id:'dubrovnik-pass-henrique',category:'Passes',title:'Dubrovnik Pass - Henrique',subtitle:'3 dias · código FW321KW4',date:'08–09 set',note:'QR será adicionado na próxima atualização.'},
{id:'dubrovnik-pass-cibele',category:'Passes',title:'Dubrovnik Pass - Cibele',subtitle:'3 dias · código JL67A7MI',date:'08–09 set',note:'QR será adicionado na próxima atualização.'},
{id:'wizz-henrique',category:'Voos',title:'Wizz Air - Henrique',subtitle:'W6 2256 · DBV → BUD · assento 4B',date:'09 set · 14:10',locator:'KWKWWW',note:'Porta fecha 13h40.'},
{id:'wizz-cibele',category:'Voos',title:'Wizz Air - Cibele',subtitle:'W6 2256 · DBV → BUD · assento 4A',date:'09 set · 14:10',locator:'KWKWWW',note:'Porta fecha 13h40.'},
{id:'flixbus-bud-lju',category:'Ônibus',title:'FlixBus Budapest → Ljubljana',subtitle:'Rota 403 · 11A/11B',date:'11 set · 06:45',locator:'338 838 9094',note:'Passaporte à mão; ticket válido impresso ou digital.'},
{id:'flight-return',category:'Voos',title:'DBV → MAD → GRU',subtitle:'LA1814 + LA1572',date:'21–22 set',note:'DBV 19h50 · chegada GRU 05h55.'}
];

export const hotels=[
{city:'Dubrovnik',name:'Lausa Dubrovnik Rooms',dates:'7→9/set',confirmation:'6859609127',pin:'4841',destination:'Lausa Dubrovnik Rooms, Dubrovnik, Croatia'},
{city:'Budapest',name:'Up Hotel Budapest',dates:'9→11/set',confirmation:'72078073634790',pin:'—',destination:'Up Hotel Budapest, Csengery utca 31, Budapest, Hungary'},
{city:'Ljubljana',name:'Under The Castle Apartments',dates:'11→13/set',confirmation:'5365081042',pin:'5211',destination:'Under The Castle Apartments, Ljubljana, Slovenia'},
{city:'Rovinj',name:'Charmy Rovinj',dates:'13→16/set',confirmation:'5693601849',pin:'9721',destination:'Charmy Rovinj, Rovinj, Croatia'},
{city:'Plitvice',name:'Villa Prica B&B',dates:'16→17/set',confirmation:'5248153221',pin:'7232',destination:'Villa Prica, Plitvica Selo 32, Croatia'},
{city:'Split',name:'Little Lion',dates:'17→21/set',confirmation:'6930013359',pin:'0663',destination:'Little Lion, Split, Croatia'}
];

export const emergencyContacts=[
{label:'Emergência Europa',value:'112',href:'tel:112'},
{label:'Seguro AIG - exterior',value:'+1 636 722 7111',href:'tel:+16367227111'},
{label:'Seguro AIG - Brasil',value:'0800 891 3294',href:'tel:08008913294'},
{label:'Consulado do Brasil - Zagreb',value:'+385 1 489 0400',href:'tel:+38514890400'}
];
export const packingChecklist=['Biquíni/sunga','Moletom/casaco leve','Agasalho para Postojna','Capa de chuva','Tênis fechado','Aqua-shoes','2 toalhas de microfibra','Protetor solar 50+','Passaportes','Cartões/Wise/Nomad','Dinheiro em espécie'];
export const pendingItems=['Locadora/carro: confirmar reserva, retirada/devolução e cross-border.','Plitvice: confirmar ingresso, Entrance 1 e horário definitivo.','Postojna + Predjama: confirmar ingresso e horário.','Ferry Vis/Jadrolinija: confirmar ida e volta de 20/set.','Krka: confirmar tour e ponto de encontro.'];
export const phrases={Croata:[['Olá','Bok / Dobar dan'],['Obrigado','Hvala'],['Por favor','Molim'],['A conta','Račun, molim']],Húngaro:[['Olá','Szia'],['Obrigado','Köszönöm'],['Por favor','Kérem'],['A conta','A számlát kérem']],Esloveno:[['Olá','Živijo / Dober dan'],['Obrigado','Hvala'],['Por favor','Prosim'],['A conta','Račun, prosim']]};
